model =
  listItems: [
    { name: "banana", qty: "all of them", __template__: 'iterative-item' },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "banana", qty: "all of them" },
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "apple", qty: "2"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
    { name: "oranges", qty: "three"},
  ]